### ISSUE TITLE
OpenStack is not respecting `enable_config_drive: False`

### ISSUE THREAD

**Issue by netoarmando** [neoave/mrack#125]
_(Most probably not the right place to report this, writing it down so we can be aware)_

```
$ grep -r config_drive *
config/provisioning-config.yaml:    enable_config_drive: False
config/mrackdb.json:        "config_drive": "True",
```
That is affecting Windows and Linux hosts. Changing mrack source code to force `config_drive` as True when provisioning hosts does not matter, same result.

**Comment by Tiboris** [comment]
This might be openstack provider configuration so it hardcodes the config drive option to true which we may not affect at all :) will close this issue for now.
