### ISSUE TITLE
8.0.8 semantic release does not support this command

### ISSUE THREAD

**Issue by Tiboris** [neoave/mrack#269]
https://github.com/neoave/mrack/blob/7e0d0383d6c026e4ed671b3f1468d320f60a2eac/.github/workflows/test-and-release.yml#L62

**Comment by Tiboris** [comment]
semantic-release version --print

**Comment by dav-pascual** [comment]
@Tiboris thanks for reporting, will try it out :)

**Comment by Tiboris** [comment]
and please remove the commit from master the command works i already tried

**Comment by Tiboris** [comment]
maybe you can try to run release on your fork without the pypi token of course to see if everything except PYPI is fine
